### ISSUE TITLE
Node v6 - TypeError thrown when validating parsed querystring objects

### ISSUE THREAD

**Issue by alexcorre** [mac-/ratify#51]
Core node module `querystring` was updated in Node v6 to return plain objects that do not prototypically extend from the JavaScript `Object`.

According to the Node [docs](https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options): 
> This means that the typical Object methods such as obj.toString(), obj.hasOwnProperty(), and others are not defined and will not work.

See Node.js PR here:
https://github.com/nodejs/node/pull/6055

breaking changes list for v5-v6:
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#querystring

As a result of this change, this packages validation of parsed query strings throws an error on this line when the var `object` is a parsed query string:

https://github.com/mac-/ratify/blob/master/lib/RouteSchemaManager.js#L117

**Comment by mac-** [comment]
Thanks for the fix! I'll try to get this merged/published tonight.

**Comment by alexcorre** [comment]
Thanks @mac- for merging. I see you released 3.0.0 to npm, but neglected to push the version bump and tag to github. Hard to verify that the release contains my fix without installing. 

Are you planning to update github with the release version bump + tag?

Thanks!

**Comment by mac-** [comment]
yeah sorry... I'll get those pushed as well
